### ISSUE TITLE
Relationships visualization

### ISSUE THREAD

**Issue by stellasia** [stellasia/neomap#15]
**Is your feature request related to a problem? Please describe.**
I can see my nodes, but not the relationships between them. 

**Describe the solution you'd like**
Would be nice to have the possibility to display relationships between nodes.

**Describe alternatives you've considered**

**Additional context**

**Comment by jexp** [comment]
Perhaps similar to flight paths on a map?

there are several "curve" plugins here: https://leafletjs.com/plugins.html

**Comment by nikita03565** [comment]
hi @stellasia!
Started working on this issue, made so far a very dirty implementation and the result looks like this:
![image](https://user-images.githubusercontent.com/33401112/120886987-5647b280-c5f9-11eb-8459-60c93162359c.png)
Wanted to ask which functionality do you want to have for relationships?
I'm planning to add 
1. one more option in `> Map rendering`
2. tooltip for relationships
3. color selection
4. relationships labels selection

**Comment by jexp** [comment]
@nikita03565 this looks really cool, thanks a lot for your work. Looking forward to see it in action.

**Comment by stellasia** [comment]
Hey @nikita03565 , that indeed looks super cool!

Regarding properties, I don't think of something else right now. In terms of map rendering, adding a new layer for relationships is probably the best way to go, and will give us more flexibility if we want to add more properties later on. I have not looked at your PR yet, will do by the end of this week!

Thanks!

**Comment by stellasia** [comment]
Yes, there is another nice stull that could be done here (not necessarily in your PR @nikita03565 ) : using a relaitonship property that contains the relationship "shape" (eg: a linestring definition), which we could use to refine the rendering (for long road segments, this might be important).

But I'd better open another issue to support this, because such property could have many different formats.

**Comment by nikita03565** [comment]
was addressed in https://github.com/stellasia/neomap/pull/98
