### ISSUE TITLE
Implement tests

### ISSUE THREAD

**Issue by stellasia** [stellasia/neomap#23]

**Comment by edumoreira1506** [comment]
Working in this issue!

**Comment by stellasia** [comment]
Let's close this one since @edumoreira1506 kindly started implementing tests in https://github.com/stellasia/neomap/pull/24 and was followed by https://github.com/stellasia/neomap/pull/25. Better tests are still needed but they will depend on further implementation improvements (creation of a "service" to manage all graph queries?).
