### ISSUE TITLE
Add a limit for the simple layer

### ISSUE THREAD

**Issue by jexp** [stellasia/neomap#26]
Eg for Panama papers with several hundred thousand addresses it otherwise breaks down.

**Comment by stellasia** [comment]
Hi Mickael!

Thanks a lot for the suggestions!

There is already a hard-coded limit of 5000, which is maybe too high. I plan to make customizable in (https://github.com/stellasia/neomap/issues/9). It will also become more visible with https://github.com/stellasia/neomap/issues/28, which is definitely a must-have!

**Comment by stellasia** [comment]
The maximum number of nodes to fetch is now customizable in 0.3.0 (default is 2000)
