### ISSUE TITLE
Not really a bug, but should investigate performance.

### ISSUE THREAD

**Issue by jexp** [stellasia/neomap#32]
When reading 50k or 100k nodes it hangs and doesn't do anything.
Trying to achieve world wide heatmap for Panama papers.

**Comment by jexp** [comment]
So I checked on panama pappers, it seems that at least in heatmap mode it can easily render 200k nodes in 3 seconds which is really cool!

Marker mode is more resource intensive.

**Comment by stellasia** [comment]
Yes, I think it's a common issue with leaflet, it has problems when it is asked to show many markers. But I'll try to investigate some other tools (I choose leaflet at first just because that was the only one I knew)

**Comment by stellasia** [comment]
Possible solution with leaflet to investigate: https://stackoverflow.com/a/43019740/4709400
