### ISSUE TITLE
Simple layer lost the tooltip field 

### ISSUE THREAD

**Issue by jexp** [stellasia/neomap#34]
So it's no longer possible to configure the tooltip property.

And it auto-generates "name" which will lead to a lot of "null" values being transfers if it's not there.

**Comment by jexp** [comment]
<img width="588" alt="Bildschirmfoto 2019-11-18 um 05 20 52" src="https://user-images.githubusercontent.com/67427/69024497-37f07680-09c3-11ea-8637-a7406e4a255d.png">

**Comment by jexp** [comment]
Perhaps it got accidentally copied to Advanced Layer? (Should be probably "custom" layer or query layer)

Now there is a tooltip -> name field there which doesn't make sense as you write a manual query.

<img width="579" alt="Bildschirmfoto 2019-11-18 um 05 26 40" src="https://user-images.githubusercontent.com/67427/69024691-2bb8e900-09c4-11ea-938e-aab0d3dcc279.png">

**Comment by jexp** [comment]
One still has to use "tooltip" in the query, like documented so that "name" there has no effect?

**Comment by stellasia** [comment]
Right, tooltip comes from the query in Advanced layer type, the input text should not be displayed.
