### ISSUE TITLE
Use the same drop-down for properties as for the label.

### ISSUE THREAD

**Issue by jexp** [stellasia/neomap#35]
For all 3 lat, lon, tooltip

Either just by calling: `call dbms.propertyKeys()`

Or if you want to go more fancy to only show keys by default that are in your label.

```
MATCH (n:$label) 
WITH n LIMIT 100 
UNWIND keys(n) as key
RETURN distinct key

```

**Comment by stellasia** [comment]
Done in 0.3.1, thanks!
