### ISSUE TITLE
Use GH npm registry for publishing

### ISSUE THREAD

**Issue by jexp** [stellasia/neomap#37]
Should be as simple as `npm login` to the GH registry and then `npm publish`.

Then folks can install from the registry directly into Desktop and also updates work automatically!

It's free for OSS https://github.com/features/packages

**Comment by stellasia** [comment]
I actually tried that during the hachathon, but never managed to make it work. 

One package was published here:
https://github.com/stellasia/neomap/packages/28018?version=0.2.0

but then I cannot get the correct link for Neo4j Desktop. Any idea?

**Comment by stellasia** [comment]
Package pushed to GitHub registry at https://github.com/stellasia/neomap/packages/28018 but requires auth to access https://npm.pkg.github.com/stellasia/neomap

So, also pushed to NPM registry, with an URL that can be used in Neo4j Desktop: https://www.npmjs.com/package/neomap

Installation instructions have been updated accordingly, just need to check the graph app gallery.
