### ISSUE TITLE
Create layer from Neo4j spatial types

### ISSUE THREAD

**Issue by stellasia** [stellasia/neomap#5]
## Goal 

Instead of reading lat/lon from node properties, it should be possible to extract that information from neo4j spatial type. 

## Proposal

Create a new "layer type" with different properties:
- Node label
- Spatial property

And then extract lat/lon from `<spatial_property>.<x, y>`

**Comment by stellasia** [comment]
https://github.com/stellasia/neomap/commit/e9ed6b6f419674f110b9c849a0be255b2f5b72f3

**Comment by jexp** [comment]
For now one can use `RETURN n.location.latitude as latitude, n.location.longitude as longitude` as a workaround.
