### ISSUE TITLE
importing shapefiles as R-trees into neo4j and map rendering it with neomap

### ISSUE THREAD

**Issue by simran0912** [stellasia/neomap#56]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by simran0912** [comment]
I want to visualize my origin-destination matrix's origin and destination using neomap. I have imported the shapefiles into neo4j and they are in r-tree format containing 4 coordinates. Is it possible to do so via neomap?

**Comment by stellasia** [comment]
Hi @simran0912 , with a Cypher query you can probably extract the coordinates to draw points, however for now neomap does not support shapes such as polygons.

If you need more help, can you share a few examples about your data?

**Comment by simran0912** [comment]
[data_github_2.zip](https://github.com/stellasia/neomap/files/4616556/data_github_2.zip)
I have attached the examples in form of images in the zip file. I have also attached the shp file, bbox data and the extracted origin destination matrix data from shp file using R in excel file. I have tried to visualize by trying to integrate neo4j with geoserver but I am facing an issue even in that. Please guide me further on how i can visualize it
