### ISSUE TITLE
Create new layer is broken

### ISSUE THREAD

**Issue by stellasia** [stellasia/neomap#77]
Clicking on "Create new layer" reloads the page without actually updating the map. On top of that, the available node labels and properties are not shown anymore.

/cc @jodom

**Comment by jodom** [comment]
Ack.




________________________________

**Comment by jodom** [comment]
You can assign this to me. Quick fix coming soon

**Comment by jodom** [comment]
Apparently, create new has always been broken, but previously was showing a giant error and crashing app. It makes sense in dev mode since we are trying create new without graph connection, and I think the fix here is better error handling.
To validate this works in prod though, a test neo4j driver that works simulating graph connection should suffice. That or requiring dev environment to connect to local neo4j installment.

Ref: https://github.com/stellasia/neomap/pull/75#discussion_r479711361

**Comment by AVSuni** [comment]
Hi guys, thanks for the effort to create this. What is the latest status of this bug? I am trying to connect to a remote database and I run into 

>  reloads the page without actually updating the map. On top of that, the available node labels and properties are not shown anymore

**Comment by jodom** [comment]
@AVSuni, sorry about that. Pushing out a fix asap.

**Comment by jodom** [comment]
Ideally the fix would go after currently open PR #79 . cc @stellasia

**Comment by AVSuni** [comment]
Thanks, I am using the stock version 0.5.0 from registry.npmjs.org. I have tried it (0.5.0) with Neo4J Desktop 1.3.8 and 1.3.4

`
_rev | "1-cc4cfed9c2d9d24fbdaa90f02fb509cb"
-- | --
name | "neomap"
dist-tags |  
latest | "0.5.1"
versions |  
0.5.0 |  
name | "neomap"
version | "0.5.0"
author |  
name | "Estelle Scifo"
private | false
neo4jDesktop |  
apiVersion | "^1.2.4"
licenseRequired | false
dependencies |  
bootstrap | "^4.3.0"
downloadjs | "^1.4.7"
graph-app-kit | "^1.0.4"
leaflet | "^1.5.1"
leaflet.heat | "^0.2.0"
leaflet.markercluster | "^1.4.1"
neo4j-driver | "^4.0.2"
react | "^16.3.2"
react-bootstrap | "^1.0.0-beta.14"
react-color | "^2.18.0"
react-confirm-alert | "^2.4.1"
react-dom | "^16.3.2"
react-redux | "^7.2.0"
react-scripts | "^3.3.1"
react-select | "^3.0.4"
redux | "^4.0.5"

 `

**Comment by stellasia** [comment]
@jodom , I managed to solve the problem on the master branch by removing the `type="submit"` on the layer's buttons. If you have some time to check and confirm this.

**Comment by stellasia** [comment]
This issue should be solved thanks to #88, new version will be released as soon as the master branch is stable again.
