### ISSUE TITLE
Hide/Collapse the 'New Layer'

### ISSUE THREAD

**Issue by johnaco** [stellasia/neomap#84]
I love this project and am trying to use it with some pre-built layers.

Visually, the left hand component where one can define layers takes a lot of real estate on the screen and it would be great if it could be collapsed.  The map itself as a layer icon that expands allowing the user to select which layers to show, which is great.

This way the user can focus on the map and layer data.

**Comment by stellasia** [comment]
Sounds like a good idea to me! We have some work in progress to improve the code quality, once this is fixed we can probably add this feature. 

(Overall, we'll have to rethink a bit the UI, the current one starts to show some limitations if we want to add more customization.)
