### ISSUE TITLE
Allow selection of database

### ISSUE THREAD

**Issue by taseroth** [stellasia/neomap#86]
Not sure if this is part of the Neo4j Desktop API, but selecting/choosing the database to use would be really helpful. In the moment, I can only use the default database 'neo4j'.

Beside that: great work. I really like NeoMap.

**Comment by nikita03565** [comment]
Sharing result of my research:
1. we can retrieve a list of available databases using query: 
`const databases = (await session.run("SHOW DATABASES")).records`
![image](https://user-images.githubusercontent.com/33401112/134171925-cb386b8d-0438-4a70-a9c6-6e2137ca2e26.png)
in this example i have 3 dbs: `neo4j`, `system` and `test`

2. we can "switch" between databases at the moment when we create session:
`const session = driver.session({database: "test"});`

This should be fairly easy to implement

**Comment by nikita03565** [comment]
@stellasia what do you think of adding `Settings` button into navbar that launches a modal?
![image](https://user-images.githubusercontent.com/33401112/134217393-509a65dc-7fe9-47a7-bbde-491aa15c8e30.png)

**Comment by stellasia** [comment]
Looks really good!

When first seeing this issue, I was thinking about configuring the database per layer, but it would maybe make overload the layer configuration. 

@taseroth , do you have a use case where you would need to overwrite a globally set database? (like comparing data in several dbs?)

**Comment by nikita03565** [comment]
hmm
when i first realized that i miss this functionality i def was thinking about global db selection.
like i have db with data for Moscow and other db with data for New York, and i want to switch between two cities and work with one of them exclusively at the moment

not arguing, just trying to understand how to implement this: globally/per layer/both?

**Comment by stellasia** [comment]
I am ok with the global setting, I think it is cleaner and probably less misleading. 

If we realize there is a real use-case, we can still add the ability to overwrite the global setting in the layer later on.

**Comment by nikita03565** [comment]
was addressed in https://github.com/stellasia/neomap/pull/100
